#!/usr/bin/env php
<?php

$composer_sources = array(
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/vendor/autoload.php',
);

foreach ($composer_sources as $file) {
    if (file_exists($file)) {
        define('EDISONLABS_COMPOSER_INSTALL', $file);
        break;
    }
}

if (!defined('EDISONLABS_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}

require EDISONLABS_COMPOSER_INSTALL;

use EdisonLabs\Metrics\Command\MetricsCommand;
use Symfony\Component\Console\Application;

// Register and run command.
$application = new Application();
$application->add(new MetricsCommand());
$application->setDefaultCommand('edisonlabs:metrics', true);
$application->run();
