#!/usr/bin/env php
<?php

//foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
//    if (file_exists($file)) {
//        define('EDISONLABS_COMPOSER_INSTALL', $file);
//        break;
//    }
//}
//
//unset($file);
//
//if (!defined('EDISONLABS_COMPOSER_INSTALL')) {
//    fwrite(
//        STDERR,
//        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
//        '    composer install' . PHP_EOL . PHP_EOL .
//        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
//    );
//
//    die(1);
//}

define('EDISONLABS_COMPOSER_INSTALL', '/home/jribeiro/Projects/git/composer/edison_metrics-8/vendor/autoload.php');

require EDISONLABS_COMPOSER_INSTALL;

use EdisonLabs\Metrics\Command\MetricsCommand;
use Symfony\Component\Console\Application;

// Register and run command.
$application = new Application();
$application->add(new MetricsCommand());
$application->setDefaultCommand('edisonlabs:metrics', true);
$application->run();
